workspace = { members = [] }

[package]
name = "rust-impl-algorithms"
version = "0.1.0"
edition = "2021"

[dev-dependencies]

[dependencies]
merkletree = "0.23.0"
pyo3 = "0.22.2"
rand = "0.8.5"
rayon = "1.10.0"
serde = "1.0.204"
